export const INC = "INC_COUNT";
export const DEC = "DEC_COUNT";
export const LOGGED_IN_USER = "LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";
export const LIKE = "LIKE"
export const INDIVIDUAL_PAGE = "INDIVIDUAL_PAGE"
export const SAVE_ITEMS = "SAVE_ITEMS"
export const SEARCH_TAG = "SEARCH_TAG"
export const SAVE_ITEMS_TRENDING="SAVE_ITEMS_TRENDING"